export type Language = 'ko' | 'en';
// Alias for backward compatibility with server-deployed code
export type AppLanguage = Language;

export const LANGUAGE_OPTIONS: { value: Language; label: string }[] = [
  { value: 'ko', label: '한국어' },
  { value: 'en', label: 'English' },
];

export function normalizeLanguage(value: string | null | undefined): Language {
  if (value === 'ko' || value === 'en') return value;
  return 'en';
}

const LANGUAGE_KEY = 'preferred-language';

export function getPreferredLanguage(): Language {
  try {
    const stored = localStorage.getItem(LANGUAGE_KEY);
    if (stored === 'ko' || stored === 'en') {
      return stored;
    }
  } catch (e) {
    console.warn('Failed to read language preference from localStorage', e);
  }
  return 'en';
}

export function setPreferredLanguage(language: Language): void {
  try {
    localStorage.setItem(LANGUAGE_KEY, language);
  } catch (e) {
    console.warn('Failed to save language preference to localStorage', e);
  }
}

export const translations = {
  ko: {
    // Settings Navigation
    apiKeys: 'API 키',
    models: '모델',
    theme: '테마',
    language: '언어',
    settings: '설정',
    settingsDescription: '설정 및 환경설정',

    // API Keys
    apiKeysTitle: 'API 키',
    apiKeysDescription: 'API 엔드포인트 및 인증',
    financialDatasetsAPI: '금융 데이터 API',
    financialDatasetsDesc: '헤지펀드 운영을 위한 금융 데이터 조회',
    anthropicAPI: 'Anthropic API',
    anthropicDesc: 'Claude 모델 (claude-4-sonnet, claude-4.1-opus 등)',
    deepseekAPI: 'DeepSeek API',
    deepseekDesc: 'DeepSeek 모델 (deepseek-chat, deepseek-reasoner 등)',
    groqAPI: 'Groq API',
    groqDesc: 'Groq 호스팅 모델 (deepseek, llama3 등)',
    googleAPI: 'Google API',
    googleDesc: 'Gemini 모델 (gemini-2.5-flash, gemini-2.5-pro)',
    openaiAPI: 'OpenAI API',
    openaiDesc: 'OpenAI 모델 (gpt-4o, gpt-4o-mini 등)',
    openrouterAPI: 'OpenRouter API',
    openrouterDesc: 'OpenRouter 모델 (gpt-4o, gpt-4o-mini 등)',
    gigachatAPI: 'GigaChat API',
    gigachatDesc: 'GigaChat 모델 (GigaChat-2-Max 등)',
    addKey: 'API 키 추가',
    updateKey: 'API 키 업데이트',
    deleteKey: 'API 키 삭제',
    deleteKeyConfirm: 'API 키를 삭제하시겠습니까?',
    copied: '복사되었습니다',

    // Models
    modelsTitle: '모델',
    modelsDescription: '로컬 및 클라우드 AI 모델',
    selectModel: '모델 선택',
    customModel: '커스텀 모델',

    // Cloud Models
    cloudModelsTitle: '클라우드 모델',
    cloudModelsDescription: '클라우드 제공자의 AI 모델',
    modelProvider: '모델 제공자',
    modelName: '모델 명',
    selectedModel: '선택된 모델',

    // Ollama
    ollamaTitle: 'Ollama',
    ollamaDescription: '로컬 호스팅 Ollama 모델',
    ollamaEndpoint: 'Ollama 엔드포인트',
    ollamaStatus: 'Ollama 상태',
    ollamaConnected: '연결됨',
    ollamaDisconnected: '연결되지 않음',
    ollamaModels: 'Ollama 모델',
    selectOllamaModel: 'Ollama 모델 선택',

    // Theme
    themeTitle: '테마',
    themeDescription: '테마 및 표시 설정',
    lightTheme: '라이트',
    darkTheme: '다크',
    systemTheme: '시스템',
    lightThemeDesc: '깔끔하고 밝은 인터페이스',
    darkThemeDesc: '편안한 다크 인터페이스',
    systemThemeDesc: '시스템 설정을 따릅니다',
    themeCustomize: '테마를 선택하거나 시스템 설정에 따라 자동 전환하세요.',

    // Language Settings
    languageTitle: '언어',
    languageDescription: '표시 언어 선택',
    korean: '한국어',
    english: 'English',

    // Left Sidebar (Flows)
    flows: '플로우',
    searchFlows: '플로우 검색...',
    loadingFlows: '플로우 불러오는 중...',
    recentFlows: '최근 플로우',
    templates: '템플릿',
    noFlowsSaved: '저장된 플로우가 없습니다',
    createFirstFlow: '첫 플로우를 만들어 시작하세요',
    noFlowsFound: '검색된 플로우가 없습니다',
    createNewFlow: '새 플로우 만들기',
    saveFlow: '플로우 저장',

    // Right Sidebar (Components)
    components: '컴포넌트',
    searchComponents: '컴포넌트 검색...',
    loadingComponents: '컴포넌트 불러오는 중...',
    noComponentsAvailable: '사용 가능한 컴포넌트가 없습니다',
    componentsWillAppear: '컴포넌트가 로드되면 여기 표시됩니다',
    noComponentsFound: '검색된 컴포넌트가 없습니다',

    // Component Groups
    startNodes: '시작 노드',
    analystNodes: '분석가',
    swarmNodes: '스웜',
    endNodes: '종료 노드',
    portfolioInput: '포트폴리오 입력',
    stockInput: '주식 입력',
    portfolioManager: '포트폴리오 매니저',
    dataWizards: '데이터 위자드',
    marketMavericks: '마켓 매버릭스',
    valueInvestors: '가치 투자자',

    // Node Descriptions
    stockInputDescription: '종목을 입력하고 이 노드를 분석가에 연결하여 인사이트를 생성하세요.',
    portfolioManagerDescription: '분석가의 입력을 바탕으로 투자 결정을 생성합니다.',
    portfolioInputDescription: '보유 종목, 수량, 가격을 입력하고 분석가 노드에 연결하세요.',

    // Node UI
    tickers: '종목 코드',
    tickersTooltip: '여러 종목을 입력할 때는 쉼표(,)로 구분하세요. 예: AAPL,NVDA,TSLA',
    enterTickers: '예: AAPL,NVDA,TSLA',
    run: '실행',
    singleRun: '단일 실행',
    backtestRun: '백테스트',
    advanced: '고급 설정',
    noRunModeFound: '실행 모드를 찾을 수 없습니다',
    availableCash: '가용 현금',
    positions: '포지션',
    positionsTooltip: '종목, 수량, 매매가로 포지션을 추가하세요',
    addPosition: '포지션 추가',
    ticker: '종목',
    quantity: '수량',
    price: '가격',
    startDate: '시작일',
    endDate: '종료일',
    nodeStatus: '상태',
    nodeIdle: '대기',
    nodeModel: '모델',
    output: '출력',

    // Agent Output Dialog
    logTitle: '활동 로그',
    analysisTitle: '분석 결과',
    tickerLabel: '종목',
    noActivity: '활동 기록이 없습니다',
    analysisInProgress: '분석 진행 중...',
    analysisComplete: '분석 결과가 없습니다',
    analysisFailed: '분석 실패',
    noAnalysisAvailable: '분석 결과 없음',
    noAnalysisForTicker: '해당 종목의 분석 결과가 없습니다',
    copyClipboard: '클립보드에 복사',
    copy: '복사',
    summaryFor: '종목 요약:',
    
    // Agent Output Dialog Dynamic Keys
    log: '로그',
    analysis: '분석',
    signal: '신호',
    confidence: '신뢰도',
    reasoning: '추론/상세내용',
    metrics: '측정 지표',
    
    // Analyst specific keys
    PRICE_RATIOS_SIGNAL: '가격 비율 신호',
    INSIDER_TRADING: '내부자 거래',
    NEWS_SENTIMENT: '뉴스 센티멘트',
    PROFITABILITY_SIGNAL: '수익성 신호',
    GROWTH_SIGNAL: '성장성 신호',
    FINANCIAL_HEALTH_SIGNAL: '재무 건전성 신호',
    Trend_Following: '추세 추종',
    Mean_Reversion: '평균 회귀',
    Momentum: '모멘텀',
    Volatility: '변동성',

    // Investment Report Dialog
    investmentReport: '투자 보고서',
    summary: '요약',
    analystSignals: '애널리스트 신호',
    recommendedActions: '애널리스트 신호를 기반으로 한 최종 투자 판단',
    tickerCol: '종목',
    priceCol: '가격',
    actionCol: '행동',
    quantityCol: '수량',
    confidenceCol: '신뢰도',
    reasoningCol: '근거',
    agentCol: '에이전트',
    signalCol: '신호',
    shares: '주',
    longAction: '매수',
    shortAction: '매도',
    holdAction: '관망',
    bullish: '강세',
    bearish: '약세',
    neutral: '중립',

    // Status Labels
    statusIdle: '대기',
    statusRunning: '실행 중',
    statusComplete: '완료',
    statusError: '오류',
    statusWaiting: '대기 중',

    // Bottom Panel
    progressTitle: '진행 상황',
    outputTitle: '출력',
    backtestTitle: '백테스트',

    // Stock Analysis Tab
    stockAnalysis: '종목 분석',
    stockAnalysisDesc: '종목을 검색하고 원하는 에이전트를 선택해 상세 분석 보고서를 받으세요.',
    activeTicker: '활성 종목',
    period: '기간',
    workspaceSync: '워크스페이스 동기화',
    workspaceSyncOn: '동기화 켜짐',
    workspaceSyncOff: '동기화 꺼짐',
    noTickerSelected: '종목 미선택',
    customRange: '직접 지정',
    applyPresetPeriod: '빠른 기간 선택',
    selectAll: '모두 선택',
    stop: '중지',
    runAnalysis: '분석 실행',
    enterAndRun: '종목 입력 후 실행',
    waitingStatus: '대기',
    runningStatus: '분석 중',
    completeStatus: '완료',
    errorStatus: '오류',
    finalDecision: '최종 투자 결정',
    noResultsYet: '종목과 에이전트를 선택한 후 분석을 실행하세요.',

    // Data Sandbox Tab
    dataSandbox: '데이터 샌드박스',
    dataSandboxDesc: '실제 데이터를 가져와 수치를 수정한 후 에이전트 분석을 실행하세요.',
    fetchData: '데이터 가져오기',
    reFetch: '다시 가져오기',
    fetching: '가져오는 중...',
    fetchFirst: '종목을 입력하고 "데이터 가져오기"를 클릭하세요.',
    metricsTab: '재무 지표',
    lineItemsTab: '세부 항목',
    trendsTab: '트렌드',
    resultsTab: '분석 결과',
    originalValue: '원본값',
    overrideValue: '수정값',
    resetOverrides: '수정 초기화',
    runWithOverrides: '수정값으로 분석 실행',
    noLineItems: '세부 항목 데이터가 없습니다.',
    latestClose: '최근 종가',
    periodReturn: '기간 수익률',
    dataRange: '데이터 기간',
    tradingDays: '거래일 수',
    mismatchBadgeTitle: 'metrics와 line_items[0] 값 불일치',
    mismatchBadgeTooltip: 'metrics와 line_items[0] 값이 다릅니다',
    // i18n 6-B additions
    analystsLabel: '분석가',
    closePriceTrend: '종가 추이',
    collapseDetails: '상세 접기',
    dataSandboxOverridesAvailable: '{ticker} · {count}개 수정값 준비됨',
    dataSandboxOverridesUnavailable: '현재 종목에 저장된 Data Sandbox 수정값 없음',
    endDateLabel: '종료일',
    exampleInvalidOverride: '예: 3.77B, 1200000',
    exampleMetricOverride: '예: 3.77B',
    exampleTicker: '예: AAPL',
    expandDetails: '상세 펼치기',
    fetchingData: '데이터를 가져오는 중...',
    financialFieldCapitalExpenditure: '설비투자',
    financialFieldCashAndEquivalents: '현금성자산',
    financialFieldDebtToEquity: '부채비율',
    financialFieldDepreciationAndAmortization: '감가상각비',
    financialFieldEarningsPerShare: '주당순이익 (EPS)',
    financialFieldEbitda: 'EBITDA',
    financialFieldFreeCashFlow: '잉여현금흐름',
    financialFieldGrossMargin: '매출총이익률',
    financialFieldGrossProfit: '매출총이익',
    financialFieldInterestExpense: '이자비용',
    financialFieldNetIncome: '순이익',
    financialFieldNetMargin: '순이익률',
    financialFieldOperatingCashFlow: '영업현금흐름',
    financialFieldOperatingIncome: '영업이익',
    financialFieldOperatingMargin: '영업이익률',
    financialFieldPriceToBookRatio: 'PBR',
    financialFieldPriceToEarningsRatio: 'PER',
    financialFieldPriceToSalesRatio: 'PSR',
    financialFieldResearchAndDevelopment: '연구개발비',
    financialFieldReturnOnAssets: 'ROA',
    financialFieldReturnOnEquity: 'ROE',
    financialFieldReturnOnInvestedCapital: 'ROIC',
    financialFieldRevenue: '매출액',
    financialFieldShareholdersEquity: '자기자본',
    financialFieldTotalAssets: '총자산',
    financialFieldTotalDebt: '총차입금',
    financialFieldTotalLiabilities: '총부채',
    lineItemsDescription: '기간별 세부 재무 항목입니다. 셀을 직접 수정할 수 있습니다.',
    loadingCharts: '차트 로딩 중...',
    marketCapLabel: '시가총액',
    metricsField: '항목',
    modelLabel: '모델',
    noMetricsToDisplay: '표시할 지표가 없습니다.',
    noPriceData: '가격 데이터가 없습니다.',
    overrideCountLabel: '수정됨: {count}개 항목',
    overrideFormatHelp: '입력 형식: 약식(3.77B · 1.2M · 500K) 또는 전체 숫자(3770000000) 모두 가능. 비율은 소수(0.35) 또는 퍼센트(35) 둘 다 가능.',
    overrideInstruction: '수정값을 입력하면 에이전트 분석 시 원본 대신 사용됩니다. 빈칸은 원본 유지.',
    periodColumn: '기간',
    runAnalysisButton: '분석 실행',
    saveToDbButton: '결과 DB 저장',
    savedToDbSuccess: '결과가 성공적으로 저장되었습니다.',
    savedToDbError: '결과 저장에 실패했습니다.',
    selectAgentsAndRun: '에이전트를 선택하고 분석을 실행하세요.',
    selectAllAgents: '모두 선택',
    startDateLabel: '시작일',
    stopButton: '중지',
    tickerCodeLabel: '종목 코드',
    useDataSandboxOverrides: 'Data Sandbox 수정값 사용',
    sandboxLabel: '샌드박스',
    volumeTrend: '거래량 추이',
    // 성장률 필드
    financialFieldRevenueGrowth: '매출 성장률',
    financialFieldEarningsGrowth: '순이익 성장률',
    financialFieldOperatingIncomeGrowth: '영업이익 성장률',
    financialFieldEbitdaGrowth: 'EBITDA 성장률',
    financialFieldFreeCashFlowGrowth: 'FCF 성장률',
    financialFieldBookValueGrowth: '장부가치 성장률',
    financialFieldEpsGrowth: 'EPS 성장률',
    // 밸류에이션 필드
    financialFieldEnterpriseValue: '기업가치 (EV)',
    financialFieldEvToEbitda: 'EV/EBITDA',
    financialFieldEvToRevenue: 'EV/매출',
    financialFieldPegRatio: 'PEG',
    financialFieldFcfYield: 'FCF 수익률',
    // 재무안정성 필드
    financialFieldCurrentRatio: '유동비율',
    financialFieldQuickRatio: '당좌비율',
    financialFieldInterestCoverage: '이자보상배율',
    // 메트릭스 서브탭
    metricsSubTabProfitability: '수익성',
    metricsSubTabValuation: '밸류에이션',
    metricsSubTabGrowthYoy: '전년대비성장',
    metricsSubTabGrowthTtm: 'TTM성장',
    metricsSubTabGrowthQoq: '전분기대비성장',
    metricsSubTabStability: '재무안정성',
    // Forward PER Annual
    forwardPerTtmLabel: 'Forward PER (TTM)',
    forwardPerAnnualFy0Label: 'Forward PER (FY0 연간)',
    forwardPerAnnualFy1Label: 'Forward PER (FY+1 연간)',
    forwardEpsFy0Label: '예측 EPS (FY0)',
    forwardEpsFy1Label: '예측 EPS (FY+1)',
    annualEstimateTableTitle: '연간 EPS 컨센서스',
    annualEstimateUnavailable: 'FY0/FY+1 연간 컨센서스 없음',
    forwardPerCardSubtitleAnnual: '연간 기준 (FY0/FY+1)',
    // Analyst Report Dashboard
    reportHeaderSave: '저장',
    reportHeaderCompareSource: '원문 비교',
    dcfValuationTitle: 'DCF 밸류에이션',
    multiplesTitle: '이익·멀티플',
    verdictTitle: '종합 의견',
    bearThesisTitle: '약세 논거',
    bullThesisTitle: '강세 논거',
    riskTitle: '리스크',
    crosscheckTitle: '교차 검증',
    crosscheckProgress: '{done}/{total} 항목 확인',
    analystStripTotal: '에이전트 {total}개',
    viewFullConsensus: '전체 의견 보기',
    signalBuy: '매수',
    signalHold: '보유',
    signalSell: '매도',
    signalBull: '강세',
    signalNeu: '중립',
    signalBear: '약세',
    // Report v5 - TOC and body
    reportTocTitle: '목차',
    reportSourcesTitle: '출처',
    reportSection01: '결론 요약',
    reportSection02: '밸류에이션 — DCF',
    reportSection03: '멀티플 — 이익 정상화 가설',
    reportSection04: '리스크와 반대 근거',
    reportSection05: '크로스체크 가이드',
    reportSection06: '원문 추적 · 출처',
    reportEvidenceBear: '약세',
    reportEvidenceBull: '강세',
    reportEvidenceNeutral: '중립',
    reportKeyNumbers: '핵심 숫자',
    reportSourcesLabel: '출처',
    reportEmptySection: '이 섹션에 적용할 데이터가 없습니다.',
    tickerSwitcherLabel: '종목 전환',
    citationAutoNote: '자동 분류 — 원문 대조로 정확성을 확인하세요.',
    sensitivityTitle: 'WACC × 성장률 — 안전마진 민감도',
    sensitivityCurrentAssumption: '현재 가정',
    mobileTocLabel: '섹션',
    // Report v5 - Header
    reportSubtitleMeta: '{period} · {dateRange} · {model}',
    pdfExportButton: 'PDF',
    compareSourceButton: '원문 대조',
    refreshMarketDataButton: '시세 갱신',
    reportGeneratedAtLabel: '보고서 생성',
    marketDataUpdatedAtLabel: '시세 갱신',
    currentPriceHelp: 'yfinance 기반 실시간 시세입니다. 시세 갱신 버튼을 누르면 서버 캐시를 우회해 현재가격과 관련 시장 데이터를 다시 가져옵니다.',
    marginOfSafetyHelp: '안전가는 1주당 내재가치 또는 DCF 적정가입니다. 뒤의 %는 최신 현재가 대비 안전가가 얼마나 높거나 낮은지 다시 계산한 값입니다.',
    reportGeneratedAtHelp: '이 보고서가 실제로 생성 완료된 시점입니다. 이전 분석을 복원한 경우 당시 생성시점이 유지됩니다.',
    marketDataUpdatedAtHelp: '현재가와 Price Compass용 시장 데이터가 마지막으로 갱신된 시점입니다.',
    verdictBuy: '↑매수·강세',
    verdictSell: '↓매도·약세',
    verdictHold: '→보유·중립',
    periodLabelHeader: '기간',
    // Report v5 - Target data sidebar
    targetDataTitle: '핵심 타겟 데이터',
    targetEpsLabel: '선행 12M 컨센 EPS',
    targetEpsSubtitle: '12개월 선행 추정',
    targetIntrinsicLabel: '1주당 내재가치',
    targetIntrinsicSubtitle: 'FCFF DCF',
    targetMarginLabel: '안전마진',
    targetMarginSubtitle: '가치평가의 결론',
    evEbitdaLabel: 'EV/EBITDA 평가',
    evEbitdaSubtitleMedian: '중앙값 EV/EBITDA {median}x · 현재 {current}x',
    evEbitdaSubtitleFallback: 'EV ÷ EBITDA 중앙값 기준',
    targetCoverageLabel: '이자보상배율',
    targetCoverageSubtitle: '단기 안정성',
    targetBetaLabel: '베타',
    targetBetaSubtitle: '리스크 프레임',
    targetWaccLabel: 'WACC',
    targetWaccSubtitle: '할인율',
    targetForwardPeLabel: 'FwdPER',
    targetForwardPeSubtitle: 'Price Compass 기준',
    targetDataEmpty: '핵심 타겟 데이터가 부족합니다.',
    targetTileFromAgent: '{name} 출처',
    otherAgentsTitle: '다른 에이전트는?',
    openConsensusMatrix: '합의 매트릭스 열기',
    comingSoonLabel: 'Coming soon',
    sourceLinkUnavailable: '출처 링크 미연결',
    // Saved Analyses Browser
    savedAnalyses: '저장 분석',
    savedAnalysesSummary: '{total}건 저장됨',
    savedAnalysesEmpty: '저장된 분석이 없습니다.',
    savedDetailEmpty: '왼쪽에서 항목을 선택하세요.',
    savedAt: '저장 시각',
    restoreToTab: '다시 열기',
    exportJson: 'JSON 내보내기',
    delete: '삭제',
    confirmDelete: '{ticker} 저장을 삭제하시겠습니까?',
    prev: '이전',
    next: '다음',
    loading: '불러오는 중...',
    filterSource: '소스',
    filterSourceAll: '전체',
    filterSourceStock: '종목 분석',
    filterSourceSandbox: '데이터 샌드박스',
    filterTicker: '티커',
    filterFrom: '시작일',
    filterTo: '종료일',
    savedRequestSnapshot: '요청 스냅샷',
    savedNoDecisions: '저장된 결과에 결정 데이터가 없습니다.',
    // Data quality null-score keys
    dataInsufficient: '데이터 부족',
    scoreOnHold: '평가 보류',
    dataCoverageLabel: '데이터 충실도 {pct}%',
    nullScoreTooltip: '이 항목은 원천 데이터가 부족해 점수를 계산하지 않았습니다.',
    targetDataCoverageLow: '데이터 커버리지가 낮아 핵심 타겟을 보류했습니다.',
    verdictOnHold: '판단 보류',
    // Price Compass Bar
    pcbTitle: '가격 나침반',
    pcbCurrent: '현재가',
    pcbDcf: 'DCF 내재가치',
    pcbMosBuy: '안전마진 매수가 ({pct}%)',
    pcbConsensus: '증권사 컨센서스',
    pcbTrailingPer: 'TTM PER 함의가',
    pcbFwdPerFy0: '연간 함의가 (FY0)',
    pcbFwdPerFyN: '연간 함의가 (FY+N)',
    pcbBetaBand: '베타 ±1σ 범위 (β={beta})',
    pcbEditPer: 'PER 편집',
    pcbResetPer: 'PER 초기화',
    pcbMissing: '표시할 가격 데이터 부족',
    // @deprecated v4 — pcb* keys kept for backward compat
    // Price Compass Panel v4 (pcp*)
    pcpTitle: 'Price Compass',
    pcpSubtitle: '베타 시나리오 × 증권사 목표가',
    pcpHelp: 'β {beta} 기준 ±2σ 변동 레인지에 {n}개 증권사 목표가 매핑',
    pcpLegendBear: '약세 · 2σ',
    pcpLegendBull: '강세 · 2σ',
    pcpLegendCurrent: '현재가',
    pcpLegendConsensus: '컨센서스',
    pcpPerTtm: 'PER(TTM)',
    pcpEpsTtm: 'EPS(TTM)',
    pcpFwdEps: 'FwdEPS',
    pcpEpsCurFy: 'EPS(현FY)',
    pcpPerCurFy: 'PER(현FY)',
    pcpHighTarget: '최고 타겟',
    pcpGroupCurrentFy: '현FY 추정',
    pcpGroupTargets: '가격/타겟',
    pcpTtmHelp: 'TTM은 최근 12개월 실적 기준입니다. EPS(TTM)와 PER(TTM)은 같은 기간 기준으로 묶어 봅니다.',
    pcpCurFyHelp: '현FY는 현재 회계연도 전체 추정치입니다. PER(현FY)은 현재가를 EPS(현FY)로 나눈 값입니다.',
    pcpFwdHelp: 'Forward는 다음 회계연도 추정치입니다. FwdPER은 현재가 대비 다음 연도 EPS 기준 배수이며, 데이터가 없을 때는 컨센서스 ÷ 현FY EPS로 대체 표시합니다.',
    pcpTargetsHelp: '현재가, 증권사 컨센서스, 최고 목표가를 한 곳에 모은 가격 기준 박스입니다.',
    pcpDcf: 'DCF 내재가치',
    pcpMos: '안전마진 매수가 ({pct}%)',
    pcpBetaFrameTitle: '베타 · 변동성 프레임',
    pcpBetaLabel: '베타 (β)',
    pcpBetaSub: '시장 대비 변동성',
    pcpSigmaLabel: '연간 변동성 (σ)',
    pcpSigmaSub: '시장 14% × β 환산',
    pcpBetaExplain: 'β {beta} → 시장이 1% 움직일 때 {ticker} 가격은 평균 {beta}% 움직임. ±2σ 시나리오에서 가격은 {low} ~ {high} 사이에서 약 95% 확률로 형성.',
    pcpOpinionTitle: '분석가 의견 분포',
    pcpOpinionAvg: '평균 목표가',
    pcpOpinionMedian: '중앙값',
    pcpOpinionStdev: '표준편차',
    pcpOpinionSpread: '의견 분산도',
    pcpBrokerGridTitle: '증권사 목표가 상세',
    pcpBrokerUpdated: '{d}일 전',
    pcpBrokerFwdPer: 'FwdPER',
    pcpSignalBuy: '매수',
    pcpSignalHold: '보유',
    pcpSignalNeutral: '중립',
    pcpSignalSell: '매도',
    pcpNoBrokers: '증권사 목표가 데이터 없음 — 컨센서스만 표시',
  },
  en: {
    // Settings Navigation
    apiKeys: 'API Keys',
    models: 'Models',
    theme: 'Theme',
    language: 'Language',
    settings: 'Settings',
    settingsDescription: 'Settings and preferences',

    // API Keys
    apiKeysTitle: 'API Keys',
    apiKeysDescription: 'API endpoints and authentication',
    financialDatasetsAPI: 'Financial Datasets API',
    financialDatasetsDesc: 'For getting financial data to power the hedge fund',
    anthropicAPI: 'Anthropic API',
    anthropicDesc: 'For Claude models (claude-4-sonnet, claude-4.1-opus, etc.)',
    deepseekAPI: 'DeepSeek API',
    deepseekDesc: 'For DeepSeek models (deepseek-chat, deepseek-reasoner, etc.)',
    groqAPI: 'Groq API',
    groqDesc: 'For Groq-hosted models (deepseek, llama3, etc.)',
    googleAPI: 'Google API',
    googleDesc: 'For Gemini models (gemini-2.5-flash, gemini-2.5-pro)',
    openaiAPI: 'OpenAI API',
    openaiDesc: 'For OpenAI models (gpt-4o, gpt-4o-mini, etc.)',
    openrouterAPI: 'OpenRouter API',
    openrouterDesc: 'For OpenRouter models (gpt-4o, gpt-4o-mini, etc.)',
    gigachatAPI: 'GigaChat API',
    gigachatDesc: 'For GigaChat models (GigaChat-2-Max, etc.)',
    addKey: 'Add API Key',
    updateKey: 'Update API Key',
    deleteKey: 'Delete API Key',
    deleteKeyConfirm: 'Are you sure you want to delete this API key?',
    copied: 'Copied to clipboard',

    // Models
    modelsTitle: 'Models',
    modelsDescription: 'Local and cloud AI models',
    selectModel: 'Select Model',
    customModel: 'Custom Model',

    // Cloud Models
    cloudModelsTitle: 'Cloud Models',
    cloudModelsDescription: 'AI models from cloud providers',
    modelProvider: 'Model Provider',
    modelName: 'Model Name',
    selectedModel: 'Selected Model',

    // Ollama
    ollamaTitle: 'Ollama',
    ollamaDescription: 'Locally hosted Ollama models',
    ollamaEndpoint: 'Ollama Endpoint',
    ollamaStatus: 'Ollama Status',
    ollamaConnected: 'Connected',
    ollamaDisconnected: 'Disconnected',
    ollamaModels: 'Ollama Models',
    selectOllamaModel: 'Select Ollama Model',

    // Theme
    themeTitle: 'Theme',
    themeDescription: 'Theme and display preferences',
    lightTheme: 'Light',
    darkTheme: 'Dark',
    systemTheme: 'System',
    lightThemeDesc: 'A clean, bright interface',
    darkThemeDesc: 'A comfortable dark interface',
    systemThemeDesc: 'Use your system preference',
    themeCustomize: 'Select your preferred theme or use system setting to automatically switch between light and dark modes.',

    // Language Settings
    languageTitle: 'Language',
    languageDescription: 'Select display language',
    korean: '한국어',
    english: 'English',

    // Left Sidebar (Flows)
    flows: 'Flows',
    searchFlows: 'Search flows...',
    loadingFlows: 'Loading flows...',
    recentFlows: 'Recent Flows',
    templates: 'Templates',
    noFlowsSaved: 'No flows saved yet',
    createFirstFlow: 'Create your first flow to get started',
    noFlowsFound: 'No flows match your search',
    createNewFlow: 'Create new flow',
    saveFlow: 'Save flow',

    // Right Sidebar (Components)
    components: 'Components',
    searchComponents: 'Search components...',
    loadingComponents: 'Loading components...',
    noComponentsAvailable: 'No components available',
    componentsWillAppear: 'Components will appear here when loaded',
    noComponentsFound: 'No components match your search',

    // Component Groups
    startNodes: 'Start Nodes',
    analystNodes: 'Analysts',
    swarmNodes: 'Swarms',
    endNodes: 'End Nodes',
    portfolioInput: 'Portfolio Input',
    stockInput: 'Stock Input',
    portfolioManager: 'Portfolio Manager',
    dataWizards: 'Data Wizards',
    marketMavericks: 'Market Mavericks',
    valueInvestors: 'Value Investors',

    // Node Descriptions
    stockInputDescription: 'Enter individual stocks and connect this node to Analysts to generate insights.',
    portfolioManagerDescription: 'Generates investment decisions based on input from Analysts.',
    portfolioInputDescription: 'Enter your portfolio including tickers, shares, and prices. Connect this node to Analysts to generate insights.',

    // Node UI
    tickers: 'Tickers',
    tickersTooltip: 'Separate multiple tickers with commas (,). e.g. AAPL,NVDA,TSLA',
    enterTickers: 'e.g. AAPL,NVDA,TSLA',
    run: 'Run',
    singleRun: 'Single Run',
    backtestRun: 'Backtest',
    advanced: 'Advanced',
    noRunModeFound: 'No run mode found.',
    availableCash: 'Available Cash',
    positions: 'Positions',
    positionsTooltip: 'Add your portfolio positions with ticker, quantity, and trade price',
    addPosition: 'Add Position',
    ticker: 'Ticker',
    quantity: 'Quantity',
    price: 'Price',
    startDate: 'Start Date',
    endDate: 'End Date',
    nodeStatus: 'Status',
    nodeIdle: 'Idle',
    nodeModel: 'Model',
    output: 'Output',

    // Agent Output Dialog
    logTitle: 'Log',
    analysisTitle: 'Analysis',
    tickerLabel: 'Ticker',
    noActivity: 'No activity available',
    analysisInProgress: 'Analysis in progress...',
    analysisComplete: 'Analysis completed with no results',
    analysisFailed: 'Analysis failed',
    noAnalysisAvailable: 'No analysis available',
    noAnalysisForTicker: 'No analysis available for this ticker',
    copyClipboard: 'Copy to clipboard',
    copy: 'Copy',
    summaryFor: 'Summary for',
    
    // Agent Output Dialog Dynamic Keys
    log: 'Log',
    analysis: 'Analysis',
    signal: 'Signal',
    confidence: 'Confidence',
    reasoning: 'Reasoning',
    metrics: 'Metrics',
    
    // Analyst specific keys
    PRICE_RATIOS_SIGNAL: 'Price Ratios Signal',
    INSIDER_TRADING: 'Insider Trading',
    NEWS_SENTIMENT: 'News Sentiment',
    PROFITABILITY_SIGNAL: 'Profitability Signal',
    GROWTH_SIGNAL: 'Growth Signal',
    FINANCIAL_HEALTH_SIGNAL: 'Financial Health Signal',
    Trend_Following: 'Trend Following',
    Mean_Reversion: 'Mean Reversion',
    Momentum: 'Momentum',
    Volatility: 'Volatility',

    // Investment Report Dialog
    investmentReport: 'Investment Report',
    summary: 'Summary',
    analystSignals: 'Analyst Signals',
    recommendedActions: 'Final investment decisions based on analyst signals',
    tickerCol: 'Ticker',
    priceCol: 'Price',
    actionCol: 'Action',
    quantityCol: 'Quantity',
    confidenceCol: 'Confidence',
    reasoningCol: 'Reasoning',
    agentCol: 'Agent',
    signalCol: 'Signal',
    shares: 'shares',
    longAction: 'Long',
    shortAction: 'Short',
    holdAction: 'Hold',
    bullish: 'Bullish',
    bearish: 'Bearish',
    neutral: 'Neutral',

    // Status Labels
    statusIdle: 'Idle',
    statusRunning: 'Running',
    statusComplete: 'Complete',
    statusError: 'Error',
    statusWaiting: 'Waiting',

    // Bottom Panel
    progressTitle: 'Progress',
    outputTitle: 'Output',
    backtestTitle: 'Backtest',

    // Stock Analysis Tab
    stockAnalysis: 'Stock Analysis',
    stockAnalysisDesc: 'Search for stocks and select agents to receive detailed analysis reports.',
    activeTicker: 'Active Ticker',
    period: 'Period',
    workspaceSync: 'Workspace Sync',
    workspaceSyncOn: 'Sync On',
    workspaceSyncOff: 'Sync Off',
    noTickerSelected: 'No ticker',
    customRange: 'Custom',
    applyPresetPeriod: 'Quick range',
    selectAll: 'Select All',
    stop: 'Stop',
    runAnalysis: 'Run Analysis',
    saveToDbButton: 'Save to DB',
    savedToDbSuccess: 'Results saved successfully.',
    savedToDbError: 'Failed to save results.',
    enterAndRun: 'Enter ticker and run',
    waitingStatus: 'Waiting',
    runningStatus: 'Running',
    completeStatus: 'Complete',
    errorStatus: 'Error',
    finalDecision: 'Final Investment Decisions',
    noResultsYet: 'Enter a ticker and select agents to run analysis.',

    // Data Sandbox Tab
    dataSandbox: 'Data Sandbox',
    dataSandboxDesc: 'Fetch real data, adjust values, then run agent analysis with your overrides.',
    fetchData: 'Fetch Data',
    reFetch: 'Re-fetch',
    fetching: 'Fetching...',
    fetchFirst: 'Enter a ticker and click "Fetch Data" to begin.',
    metricsTab: 'Metrics',
    lineItemsTab: 'Line Items',
    trendsTab: 'Trends',
    resultsTab: 'Results',
    originalValue: 'Original',
    overrideValue: 'Override',
    resetOverrides: 'Reset overrides',
    runWithOverrides: 'Run with overrides',
    noLineItems: 'No line item data available.',
    latestClose: 'Latest Close',
    periodReturn: 'Period Return',
    dataRange: 'Data Range',
    tradingDays: 'Trading Days',
    mismatchBadgeTitle: 'metrics and line_items[0] value mismatch',
    mismatchBadgeTooltip: 'metrics and line_items[0] values differ',
    // i18n 6-B additions
    analystsLabel: 'Analysts',
    closePriceTrend: 'Close Price',
    collapseDetails: 'Collapse details',
    dataSandboxOverridesAvailable: '{ticker} · {count} override(s) ready',
    dataSandboxOverridesUnavailable: 'No Data Sandbox overrides saved for this ticker',
    endDateLabel: 'End',
    exampleInvalidOverride: 'e.g. 3.77B, 1200000',
    exampleMetricOverride: 'e.g. 3.77B',
    exampleTicker: 'e.g. AAPL',
    expandDetails: 'Expand details',
    fetchingData: 'Fetching data...',
    financialFieldCapitalExpenditure: 'CapEx',
    financialFieldCashAndEquivalents: 'Cash & Equivalents',
    financialFieldDebtToEquity: 'Debt to Equity',
    financialFieldDepreciationAndAmortization: 'Depreciation & Amortization',
    financialFieldEarningsPerShare: 'EPS',
    financialFieldEbitda: 'EBITDA',
    financialFieldFreeCashFlow: 'Free Cash Flow',
    financialFieldGrossMargin: 'Gross Margin',
    financialFieldGrossProfit: 'Gross Profit',
    financialFieldInterestExpense: 'Interest Expense',
    financialFieldNetIncome: 'Net Income',
    financialFieldNetMargin: 'Net Margin',
    financialFieldOperatingCashFlow: 'Operating Cash Flow',
    financialFieldOperatingIncome: 'Operating Income',
    financialFieldOperatingMargin: 'Operating Margin',
    financialFieldPriceToBookRatio: 'P/B Ratio',
    financialFieldPriceToEarningsRatio: 'P/E Ratio',
    financialFieldPriceToSalesRatio: 'P/S Ratio',
    financialFieldResearchAndDevelopment: 'R&D',
    financialFieldReturnOnAssets: 'Return on Assets',
    financialFieldReturnOnEquity: 'Return on Equity',
    financialFieldReturnOnInvestedCapital: 'ROIC',
    financialFieldRevenue: 'Revenue',
    financialFieldShareholdersEquity: "Shareholders' Equity",
    financialFieldTotalAssets: 'Total Assets',
    financialFieldTotalDebt: 'Total Debt',
    financialFieldTotalLiabilities: 'Total Liabilities',
    lineItemsDescription: 'Period-level financial line items. Edit cells directly.',
    loadingCharts: 'Loading charts...',
    marketCapLabel: 'Market Cap',
    metricsField: 'Field',
    modelLabel: 'Model',
    noMetricsToDisplay: 'No metrics to display.',
    noPriceData: 'No price data available.',
    overrideCountLabel: '{count} field(s) overridden',
    overrideFormatHelp: 'Format: shorthand (3.77B · 1.2M · 500K) or full number (3770000000). Ratios: decimal (0.35) or percent (35).',
    overrideInstruction: 'Override values replace originals during agent analysis. Leave blank to keep original.',
    periodColumn: 'Period',
    runAnalysisButton: 'Run Analysis',
    selectAgentsAndRun: 'Select agents and run analysis.',
    selectAllAgents: 'Select All',
    startDateLabel: 'Start',
    stopButton: 'Stop',
    tickerCodeLabel: 'Ticker',
    useDataSandboxOverrides: 'Use Data Sandbox overrides',
    sandboxLabel: 'Sandbox',
    volumeTrend: 'Volume',
    // Growth rate fields
    financialFieldRevenueGrowth: 'Revenue Growth',
    financialFieldEarningsGrowth: 'Earnings Growth',
    financialFieldOperatingIncomeGrowth: 'Operating Income Growth',
    financialFieldEbitdaGrowth: 'EBITDA Growth',
    financialFieldFreeCashFlowGrowth: 'FCF Growth',
    financialFieldBookValueGrowth: 'Book Value Growth',
    financialFieldEpsGrowth: 'EPS Growth',
    // Valuation fields
    financialFieldEnterpriseValue: 'Enterprise Value',
    financialFieldEvToEbitda: 'EV/EBITDA',
    financialFieldEvToRevenue: 'EV/Revenue',
    financialFieldPegRatio: 'PEG Ratio',
    financialFieldFcfYield: 'FCF Yield',
    // Stability fields
    financialFieldCurrentRatio: 'Current Ratio',
    financialFieldQuickRatio: 'Quick Ratio',
    financialFieldInterestCoverage: 'Interest Coverage',
    // Metrics subtabs
    metricsSubTabProfitability: 'Profitability',
    metricsSubTabValuation: 'Valuation',
    metricsSubTabGrowthYoy: 'Growth (YoY)',
    metricsSubTabGrowthTtm: 'Growth (TTM)',
    metricsSubTabGrowthQoq: 'Growth (QoQ)',
    metricsSubTabStability: 'Stability',
    // Forward PER Annual
    forwardPerTtmLabel: 'Forward PER (TTM)',
    forwardPerAnnualFy0Label: 'Forward PER (FY0 Annual)',
    forwardPerAnnualFy1Label: 'Forward PER (FY+1 Annual)',
    forwardEpsFy0Label: 'Est. EPS (FY0)',
    forwardEpsFy1Label: 'Est. EPS (FY+1)',
    annualEstimateTableTitle: 'Annual EPS Consensus',
    annualEstimateUnavailable: 'No FY0/FY+1 annual consensus',
    forwardPerCardSubtitleAnnual: 'Annual basis (FY0/FY+1)',
    // Analyst Report Dashboard
    reportHeaderSave: 'Save',
    reportHeaderCompareSource: 'Compare Source',
    dcfValuationTitle: 'DCF Valuation',
    multiplesTitle: 'Earnings · Multiples',
    verdictTitle: 'Verdict',
    bearThesisTitle: 'Bear Thesis',
    bullThesisTitle: 'Bull Thesis',
    riskTitle: 'Risk',
    crosscheckTitle: 'Cross-Check',
    crosscheckProgress: '{done}/{total} items checked',
    analystStripTotal: '{total} agents',
    viewFullConsensus: 'View Full Consensus',
    signalBuy: 'Buy',
    signalHold: 'Hold',
    signalSell: 'Sell',
    signalBull: 'Bull',
    signalNeu: 'Neutral',
    signalBear: 'Bear',
    // Report v5 - TOC and body
    reportTocTitle: 'Table of Contents',
    reportSourcesTitle: 'Sources',
    reportSection01: 'Conclusion',
    reportSection02: 'Valuation — DCF',
    reportSection03: 'Multiples — Earnings Normalisation',
    reportSection04: 'Risks & Counterthesis',
    reportSection05: 'Cross-check Guide',
    reportSection06: 'Source Tracking · Citations',
    reportEvidenceBear: 'BEAR',
    reportEvidenceBull: 'BULL',
    reportEvidenceNeutral: 'NEUTRAL',
    reportKeyNumbers: 'Key Numbers',
    reportSourcesLabel: 'Sources',
    reportEmptySection: 'No data available for this section.',
    tickerSwitcherLabel: 'Switch Ticker',
    citationAutoNote: 'Auto-classified — verify with original source.',
    sensitivityTitle: 'WACC × Growth — Margin-of-Safety Sensitivity',
    sensitivityCurrentAssumption: 'Current assumption',
    mobileTocLabel: 'Sections',
    // Report v5 - Header
    reportSubtitleMeta: '{period} · {dateRange} · {model}',
    pdfExportButton: 'PDF',
    compareSourceButton: 'Compare Source',
    refreshMarketDataButton: 'Refresh Price',
    reportGeneratedAtLabel: 'Report Generated',
    marketDataUpdatedAtLabel: 'Market Data',
    currentPriceHelp: 'Live market price from yfinance. Refresh Price bypasses the server cache and reloads current price plus related market data.',
    marginOfSafetyHelp: 'Safety Price is the per-share intrinsic value or DCF fair price. The % is recalculated against the latest current price.',
    reportGeneratedAtHelp: 'The timestamp when this report generation completed. Restored analyses keep their original generated time.',
    marketDataUpdatedAtHelp: 'The last time current price and Price Compass market data were refreshed.',
    verdictBuy: '↑Buy · Bull',
    verdictSell: '↓Sell · Bear',
    verdictHold: '→Hold · Neutral',
    periodLabelHeader: 'Period',
    // Report v5 - Target data sidebar
    targetDataTitle: 'Target Data',
    targetEpsLabel: '12M forward consensus EPS',
    targetEpsSubtitle: 'Forward 12-month estimate',
    targetIntrinsicLabel: 'Intrinsic Value / Share',
    targetIntrinsicSubtitle: 'FCFF DCF',
    targetMarginLabel: 'Margin of Safety',
    targetMarginSubtitle: 'Valuation conclusion',
    evEbitdaLabel: 'EV/EBITDA',
    evEbitdaSubtitleMedian: 'Median EV/EBITDA {median}x · current {current}x',
    evEbitdaSubtitleFallback: 'Median EV/EBITDA multiple',
    targetCoverageLabel: 'Interest Coverage',
    targetCoverageSubtitle: 'Short-term stability',
    targetBetaLabel: 'Beta',
    targetBetaSubtitle: 'Risk frame',
    targetWaccLabel: 'WACC',
    targetWaccSubtitle: 'Discount rate',
    targetForwardPeLabel: 'FwdPER',
    targetForwardPeSubtitle: 'Price Compass baseline',
    targetDataEmpty: 'Target data is incomplete.',
    targetTileFromAgent: 'From {name}',
    otherAgentsTitle: 'Other Agents',
    openConsensusMatrix: 'Open Consensus Matrix',
    comingSoonLabel: 'Coming soon',
    sourceLinkUnavailable: 'Source link unavailable',
    // Saved Analyses Browser
    savedAnalyses: 'Saved Analyses',
    savedAnalysesSummary: '{total} saved',
    savedAnalysesEmpty: 'No saved analyses.',
    savedDetailEmpty: 'Select an item from the list.',
    savedAt: 'Saved at',
    restoreToTab: 'Restore',
    exportJson: 'Export JSON',
    delete: 'Delete',
    confirmDelete: 'Delete saved analysis for {ticker}?',
    prev: 'Prev',
    next: 'Next',
    loading: 'Loading...',
    filterSource: 'Source',
    filterSourceAll: 'All',
    filterSourceStock: 'Stock Analysis',
    filterSourceSandbox: 'Data Sandbox',
    filterTicker: 'Ticker',
    filterFrom: 'From',
    filterTo: 'To',
    savedRequestSnapshot: 'Request snapshot',
    savedNoDecisions: 'Saved result has no decisions data.',
    // Data quality null-score keys
    dataInsufficient: 'Insufficient data',
    scoreOnHold: 'Score on hold',
    dataCoverageLabel: 'Data coverage {pct}%',
    nullScoreTooltip: 'This axis was not scored because the underlying data is insufficient.',
    targetDataCoverageLow: 'Target data is on hold due to low coverage.',
    verdictOnHold: 'Verdict on hold',
    // Price Compass Bar
    pcbTitle: 'Price Compass',
    pcbCurrent: 'Current',
    pcbDcf: 'DCF Intrinsic',
    pcbMosBuy: 'MoS Buy Price ({pct}%)',
    pcbConsensus: 'Broker Consensus',
    pcbTrailingPer: 'TTM PER Implied',
    pcbFwdPerFy0: 'Annual Implied (FY0)',
    pcbFwdPerFyN: 'Annual Implied (FY+N)',
    pcbBetaBand: 'Beta ±1σ Range (β={beta})',
    pcbEditPer: 'Edit PER',
    pcbResetPer: 'Reset PER',
    pcbMissing: 'Insufficient price data',
    // @deprecated v4 — pcb* keys kept for backward compat
    // Price Compass Panel v4 (pcp*)
    pcpTitle: 'Price Compass',
    pcpSubtitle: 'Beta scenario × Broker targets',
    pcpHelp: 'Mapping {n} broker targets onto ±2σ range from β {beta}',
    pcpLegendBear: 'Bearish · 2σ',
    pcpLegendBull: 'Bullish · 2σ',
    pcpLegendCurrent: 'Current',
    pcpLegendConsensus: 'Consensus',
    pcpPerTtm: 'PER (TTM)',
    pcpEpsTtm: 'EPS (TTM)',
    pcpFwdEps: 'Fwd EPS',
    pcpEpsCurFy: 'EPS (Cur. FY)',
    pcpPerCurFy: 'P/E (Cur. FY)',
    pcpHighTarget: 'High Target',
    pcpGroupCurrentFy: 'Current FY',
    pcpGroupTargets: 'Price / Targets',
    pcpTtmHelp: 'TTM means trailing twelve months. EPS (TTM) and PER (TTM) use the same trailing period.',
    pcpCurFyHelp: 'Current FY is the current fiscal-year estimate. P/E (Cur. FY) is current price divided by EPS (Cur. FY).',
    pcpFwdHelp: 'Forward uses next fiscal-year estimates. Fwd P/E is current price divided by next-year EPS; if next-year EPS is missing, we fall back to consensus ÷ current-FY EPS.',
    pcpTargetsHelp: 'Current price, analyst consensus, and the highest analyst target are grouped here.',
    pcpDcf: 'DCF Intrinsic',
    pcpMos: 'MoS Buy ({pct}%)',
    pcpBetaFrameTitle: 'Beta · Volatility Frame',
    pcpBetaLabel: 'Beta (β)',
    pcpBetaSub: 'vs market',
    pcpSigmaLabel: 'Annual σ',
    pcpSigmaSub: 'Market 14% × β',
    pcpBetaExplain: 'β {beta} → when the market moves 1%, {ticker} moves ~{beta}% on average. ±2σ scenarios place the price between {low} ~ {high} with ~95% probability.',
    pcpOpinionTitle: 'Analyst Opinion Distribution',
    pcpOpinionAvg: 'Avg Target',
    pcpOpinionMedian: 'Median',
    pcpOpinionStdev: 'Std Dev',
    pcpOpinionSpread: 'Opinion spread',
    pcpBrokerGridTitle: 'Broker Targets Detail',
    pcpBrokerUpdated: '{d}d ago',
    pcpBrokerFwdPer: 'Fwd P/E',
    pcpSignalBuy: 'Buy',
    pcpSignalHold: 'Hold',
    pcpSignalNeutral: 'Neutral',
    pcpSignalSell: 'Sell',
    pcpNoBrokers: 'No broker data — showing consensus only',
  }
};

export type TranslationKey = keyof typeof translations.en;

export function t(key: TranslationKey | string, language: Language = getPreferredLanguage()): string {
  const langDict = translations[language] as Record<string, string>;
  const enDict = translations.en as Record<string, string>;
  return langDict[key] || enDict[key] || key;
}
